export enum SocketEvent {
  CONNECTION = "connection",
  DISCONNECT = "disconnect",
  JOIN_CONVERSATION = "join_conversation",
  LEAVE_CONVERSATION = "leave_conversation",
  SEND_MESSAGE = "send_message",
  NEW_MESSAGE = "new_message",
  USER_ONLINE = "user_online",
  USER_OFFLINE = "user_offline",
  TYPING_START = "typing_start",
  TYPING_STOP = "typing_stop",
  TYPING = "typing",
  MESSAGE_DELIVERED = "message_delivered",
  MESSAGE_READ = "message_read",
  EDIT_MESSAGE = "edit_message",
  DELETE_MESSAGE = "delete_message",
  TOGGLE_REACTION = "toggle_reaction",
  SYNC_MESSAGE = "sync_message",
  DELIVERY_UPDATE = "delivery_update",
  READ_UPDATE = "read_update",
  MESSAGE_EDITED = "message_edited",
  MESSAGE_DELETED = "message_deleted",
  REACTION_UPDATED = "reaction_updated",
  SYNC_MESSAGES = "sync_messages",
  SERVER_ERROR = "server_error"
}
